// Copyright (c) 2025-present Mason Zhao MasonSZhao@qq.com

#pragma once

#include <d2d1_3.h>
#pragma comment(lib, "d2d1.lib")
#include <dwrite_3.h>
#pragma comment(lib, "dwrite.lib")

namespace QILD2D {

struct D2dWndIndep {
    // Factory
    static ID2D1Factory5* s_pD2D1Factory;
    static IDWriteFactory7* s_pDWriteFactory;
    static IDWriteTextFormat* s_pDWriteTextFormat16;
    static IDWriteTextFormat* s_pDWriteTextFormat14;

    static float s_lineHeight16;
    static float s_lineHeight14;

    // Font
    static IDWriteFontCollection1* s_pDWriteFontCollection;
    static IDWriteFontSetBuilder2* s_pDWriteFontSetBuilder;
    static IDWriteFontSet* s_pDWriteFontSet;
    static ID2D1StrokeStyle* s_pD2D1StrokeStyle;

    // Helper
    template <class Interface>
    static inline void SafeRelease(Interface** ppInterfaceToRelease)
    {
        if (*ppInterfaceToRelease != NULL) {
            (*ppInterfaceToRelease)->Release();
            (*ppInterfaceToRelease) = NULL;
        }
    }

    // Cout
    static HANDLE s_hCout;
};

}

#define WNDMAIN_HMENU_SYS_SETDAYBAR (WM_USER + 1)
#define WNDMAIN_HMENU_SYS_SETMINUTEBAR (WM_USER + 2)
#define WNDMAIN_HMENU_SYS_SETMULTITHREAD (WM_USER + 3)
#define WNDMAIN_HMENU_SYS_COLOR_WHITE (WM_USER + 4)
#define WNDMAIN_HMENU_SYS_COLOR_BLACK (WM_USER + 5)
#define WNDMAIN_HMENU_SYS_COLOR_GRAY (WM_USER + 6)
#define WNDMAIN_HMENU_SYS_SETCOLORTHEME (WM_USER + 7)
#define WNDMAIN_HMENU_SYS_EXCONFIGFILE (WM_USER + 8)
#define WNDMAIN_HMENU_SYS_IMCONFIGFILE (WM_USER + 9)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIOD300DESCRIPTION (WM_USER + 10)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIOD300TIMESHARING (WM_USER + 11)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIOD688DESCRIPTION (WM_USER + 12)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIOD688TIMESHARING (WM_USER + 13)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIODBJDESCRIPTION (WM_USER + 14)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIODBJTIMESHARING (WM_USER + 15)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIODSHSZDESCRIPTION (WM_USER + 16)
#define WNDMAIN_HMENU_REVIEW_LIMITPERIODSHSZTIMESHARING (WM_USER + 17)
#define WNDMAIN_HMENU_REVIEW_QUOTEPUBINSTI (WM_USER + 18)
#define WNDMAIN_HMENU_REVIEW_QUOTEPUBQUANT (WM_USER + 19)
#define WNDMAIN_HMENU_REVIEW_QUOTEPUBHOTMONEY (WM_USER + 20)
#define WNDMAIN_HMENU_HELP_ABOUT (WM_USER + 21)
#define WNDLIMITPERIODTIMESHARING_WND_R2C2 (WM_USER + 22)
#define WNDLIMITPERIODTIMESHARING_WND_R2C3 (WM_USER + 23)
#define WNDLIMITPERIODTIMESHARING_WND_R2C4 (WM_USER + 24)
#define WNDLIMITPERIODTIMESHARING_WND_R2C5 (WM_USER + 25)
#define WNDLIMITPERIODTIMESHARING_WND_R2C6 (WM_USER + 26)
#define WNDLIMITPERIODTIMESHARING_WND_R2C7 (WM_USER + 27)
#define WNDLIMITPERIODTIMESHARING_WND_R2C8 (WM_USER + 28)
#define WNDLIMITPERIODTIMESHARING_WND_R3C2 (WM_USER + 29)
#define WNDLIMITPERIODTIMESHARING_WND_R3C3 (WM_USER + 30)
#define WNDLIMITPERIODTIMESHARING_WND_R3C4 (WM_USER + 31)
#define WNDLIMITPERIODTIMESHARING_WND_R3C5 (WM_USER + 32)
#define WNDLIMITPERIODTIMESHARING_WND_R3C6 (WM_USER + 33)
#define WNDLIMITPERIODTIMESHARING_WND_R3C7 (WM_USER + 34)
#define WNDLIMITPERIODTIMESHARING_WND_R3C8 (WM_USER + 35)
#define WNDLIMITPERIODTIMESHARING_WND_R4C2 (WM_USER + 36)
#define WNDLIMITPERIODTIMESHARING_WND_R4C3 (WM_USER + 37)
#define WNDLIMITPERIODTIMESHARING_WND_R4C4 (WM_USER + 38)
#define WNDLIMITPERIODTIMESHARING_WND_R4C5 (WM_USER + 39)
#define WNDLIMITPERIODTIMESHARING_WND_R4C6 (WM_USER + 40)
#define WNDLIMITPERIODTIMESHARING_WND_R4C7 (WM_USER + 41)
#define WNDLIMITPERIODTIMESHARING_WND_R4C8 (WM_USER + 42)
#define WNDLIMITPERIODTIMESHARING_WND_R5C2 (WM_USER + 43)
#define WNDLIMITPERIODTIMESHARING_WND_R5C3 (WM_USER + 44)
#define WNDLIMITPERIODTIMESHARING_WND_R5C4 (WM_USER + 45)
#define WNDLIMITPERIODTIMESHARING_WND_R5C5 (WM_USER + 46)
#define WNDLIMITPERIODTIMESHARING_WND_R5C6 (WM_USER + 47)
#define WNDLIMITPERIODTIMESHARING_WND_R5C7 (WM_USER + 48)
#define WNDLIMITPERIODTIMESHARING_WND_R5C8 (WM_USER + 49)
#define WNDLIMITPERIODTIMESHARING_WND_R6C2 (WM_USER + 50)
#define WNDLIMITPERIODTIMESHARING_WND_R6C3 (WM_USER + 51)
#define WNDLIMITPERIODTIMESHARING_WND_R6C4 (WM_USER + 52)
#define WNDLIMITPERIODTIMESHARING_WND_R6C5 (WM_USER + 53)
#define WNDLIMITPERIODTIMESHARING_WND_R6C6 (WM_USER + 54)
#define WNDLIMITPERIODTIMESHARING_WND_R6C7 (WM_USER + 55)
#define WNDLIMITPERIODTIMESHARING_WND_R6C8 (WM_USER + 56)